server:
  port: 8081

spring:
  datasource:
    url: ${AUTH_DB_URL:jdbc:postgresql://localhost:5432/auth_db}
    username: ${AUTH_DB_USERNAME:postgres}
    password: ${AUTH_DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
  security:
    user:
      name: disabled
      password: disabled

application:
  admin:
    seed:
      full-name: ${AUTH_ADMIN_FULL_NAME:System Administrator}
      email: ${AUTH_ADMIN_EMAIL:admin@event.local}
      password: ${AUTH_ADMIN_PASSWORD:Admin12345}
  security:
    jwt:
      secret: ${AUTH_JWT_SECRET:TXlTdXBlclNlY3JldEtleUZvckp3dEF1dGhTZXJ2aWNlMTIzNDU2Nzg5MDEyMzQ1Njc4OTA=}
      expiration-ms: ${AUTH_JWT_EXPIRATION_MS:86400000}
